from models import Song


def initialize_song_pool():
    """
        "Base de datos" de las canciones. Aquí se pueden agregar, quitar o modificar los valores por canción
    """
    data = [
        ("All Star", "Smash Mouth", "Fush Yu Mang", 0.58, 0.83, -3.76, 93.2),
        (
            "I Want it That Way",
            "Backstreet Boys",
            "Millennium",
            0.58,
            0.79,
            -5.55,
            98.0,
        ),
        ("Believe", "Cher", "Believe", 0.62, 0.75, -6.05, 102.0),
        ("Blue (Da Ba Dee)", "Eiffel 65", "Europop", 0.62, 0.83, -4.33, 128.0),
        (
            "Genie in a Bottle",
            "Christina Aguilera",
            "Christina Aguilera",
            0.64,
            0.78,
            -5.42,
            95.0,
        ),
        (
            "Livin' la Vida Loca",
            "Ricky Martin",
            "Ricky Martin",
            0.7,
            0.85,
            -4.51,
            119.0,
        ),
        ("Bailamos", "Enrique Iglesias", "Bailamos", 0.62, 0.75, -5.8, 98.0),
        (
            "Mambo No. 5 (A Little Bit Of...)",
            "Lou Bega",
            "A Little Bit Of Mambo",
            0.71,
            0.85,
            -4.51,
            166.0,
        ),
        ("Smooth", "Santana", "Supernatural", 0.62, 0.75, -5.8, 98.0),
        ("No Scrubs", "TLC", "FanMail", 0.71, 0.85, -5.8, 112.0),
        ("Wild Wild West", "Will Smith", "Wild Wild West", 0.68, 0.8, -5.8, 98.0),
        ("I Knew I Loved You", "Savage Garden", "Affirmation", 0.62, 0.75, -5.8, 98.0),
        (
            "What a Girl Wants",
            "Christina Aguilera",
            "Christina Aguilera",
            0.68,
            0.8,
            -5.8,
            98.0,
        ),
        ("Unpretty", "TLC", "FanMail", 0.62, 0.75, -5.8, 98.0),
        ("California Love", "2Pac", "All Eyez on Me", 0.75, 0.85, -4.51, 112.0),
        ("Barbie Girl", "Aqua", "Aquarium", 0.75, 0.85, -4.51, 128.0),
        ("Kiss From a Rose", "Seal", "Seal II", 0.62, 0.75, -5.8, 98.0),
        (
            "Gonna Make You Sweat (Everybody Dance Now)",
            "C+C Music Factory",
            "Gonna Make You Sweat",
            0.75,
            0.85,
            -4.51,
            128.0,
        ),
        (
            "Macarena (Bayside Boys Mix)",
            "Los Del Rio",
            "Macarena",
            0.75,
            0.85,
            -4.51,
            128.0,
        ),
        ("Ray of Light", "Madonna", "Ray of Light", 0.68, 0.8, -5.8, 98.0),
        (
            "U Can't Touch This",
            "MC Hammer",
            "Please Hammer Don't Hurt 'Em",
            0.75,
            0.85,
            -4.51,
            104.0,
        ),
        (
            "Jump Around",
            "House of Pain",
            "Shamrocks & Shenanigans",
            0.75,
            0.85,
            -4.51,
            116.0,
        ),
        (
            "Insane in the Brain",
            "Cypress Hill",
            "Black Sunday",
            0.75,
            0.85,
            -4.51,
            116.0,
        ),
        ("Enter Sandman", "Metallica", "Metallica", 0.25, 0.85, -3.0, 106.0),
        ("November Rain", "Guns N Roses", "Use Your Illusion I", 0.35, 0.8, -5.0, 75.0),
        (
            "Under the Bridge",
            "Red Hot Chili Peppers",
            "Blood Sugar Sex Magik",
            0.45,
            0.75,
            -6.0,
            90.0,
        ),
        ("Smells Like Teen Spirit", "Nirvana", "Nevermind", 0.35, 0.8, -5.0, 94.0),
        ("Come As You Are", "Nirvana", "Nevermind", 0.35, 0.8, -5.0, 98.0),
        ("Lithium", "Nirvana", "Nevermind", 0.35, 0.8, -5.0, 98.0),
        ("Polly", "Nirvana", "Nevermind", 0.35, 0.8, -5.0, 98.0),
        ("Territorial Pissings", "Nirvana", "Nevermind", 0.35, 0.8, -5.0, 98.0),
        ("Drain You", "Nirvana", "Nevermind", 0.35, 0.8, -5.0, 98.0),
        ("Lounge Act", "Nirvana", "Nevermind", 0.35, 0.8, -5.0, 98.0),
        ("Stay Away", "Nirvana", "Nevermind", 0.35, 0.8, -5.0, 98.0),
        ("On a Plain", "Nirvana", "Nevermind", 0.35, 0.8, -5.0, 98.0),
        ("Something in the Way", "Nirvana", "Nevermind", 0.35, 0.8, -5.0, 98.0),
        ("Endless Nameless", "Nirvana", "Nevermind", 0.35, 0.8, -5.0, 98.0),
        (
            "Oops!... I Did It Again",
            "Britney Spears",
            "Oops!... I Did It Again",
            0.68,
            0.8,
            -5.8,
            98.0,
        ),
        ("Someone Like You", "Adele", "21", 0.48, 0.52, -6.3, 67.0),
        (
            "Shut Up and Dance",
            "WALK THE MOON",
            "TALKING IS HARD",
            0.70,
            0.85,
            -4.2,
            128.0,
        ),
        ("Bad Romance", "Lady Gaga", "The Fame Monster", 0.76, 0.88, -4.9, 119.0),
        (
            "Sweet Child o' Mine",
            "Guns N' Roses",
            "Appetite for Destruction",
            0.56,
            0.78,
            -5.5,
            125.0,
        ),
        ("Despacito", "Luis Fonsi ft. Daddy Yankee", "Vida", 0.85, 0.88, -4.4, 89.0),
        ("Wannabe", "Spice Girls", "Spice", 0.82, 0.75, -6.7, 110.0),
        ("Rolling in the Deep", "Adele", "21", 0.67, 0.76, -5.8, 105.0),
        ("Bohemian Rhapsody", "Queen", "A Night at the Opera", 0.45, 0.72, -7.5, 142.0),
        ("Shake It Off", "Taylor Swift", "1989", 0.78, 0.85, -5.2, 160.0),
        ("Billie Jean", "Michael Jackson", "Thriller", 0.70, 0.90, -6.4, 117.0),
        (
            "Hollaback Girl",
            "Gwen Stefani",
            "Love. Angel. Music. Baby.",
            0.76,
            0.88,
            -4.5,
            110.0,
        ),
        ("Eye of the Tiger", "Survivor", "Eye of the Tiger", 0.64, 0.87, -5.0, 109.0),
        ("Sicko Mode", "Travis Scott", "ASTROWORLD", 0.85, 0.92, -3.9, 155.0),
        (
            "Can't Help Falling In Love",
            "Elvis Presley",
            "Blue Hawaii",
            0.53,
            0.48,
            -9.6,
            95.0,
        ),
        ("Firework", "Katy Perry", "Teenage Dream", 0.68, 0.82, -5.0, 124.0),
        ("Hotel California", "Eagles", "Hotel California", 0.52, 0.74, -5.4, 75.0),
        (
            "Party in the USA",
            "Miley Cyrus",
            "The Time of Our Lives",
            0.78,
            0.80,
            -4.8,
            96.0,
        ),
        ("Sweet Caroline", "Neil Diamond", "Sweet Caroline", 0.62, 0.69, -7.2, 125.0),
        (
            "Stairway to Heaven",
            "Led Zeppelin",
            "Led Zeppelin IV",
            0.40,
            0.62,
            -8.5,
            83.0,
        ),
        ("Wrecking Ball", "Miley Cyrus", "Bangerz", 0.65, 0.88, -5.3, 120.0),
        ("Take On Me", "a-ha", "Hunting High and Low", 0.80, 0.75, -5.6, 84.0),
        (
            "Sweet Home Alabama",
            "Lynyrd Skynyrd",
            "Second Helping",
            0.54,
            0.82,
            -6.4,
            98.0,
        ),
        ("Hotline Bling", "Drake", "Views", 0.73, 0.68, -9.8, 135.0),
        (
            "Waka Waka (This Time for Africa)",
            "Shakira",
            "Sale el Sol",
            0.79,
            0.87,
            -3.7,
            127.0,
        ),
        (
            "Livin' on a Prayer",
            "Bon Jovi",
            "Slippery When Wet",
            0.65,
            0.84,
            -5.3,
            122.0,
        ),
        ("Shape of You", "Ed Sheeran", "÷", 0.78, 0.86, -4.8, 95.0),
        ("Radioactive", "Imagine Dragons", "Night Visions", 0.65, 0.87, -3.4, 136.0),
        ("Chandelier", "Sia", "1000 Forms of Fear", 0.70, 0.76, -4.6, 90.0),
        ("Jolene", "Dolly Parton", "Jolene", 0.63, 0.65, -8.2, 108.0),
        ("Dancing Queen", "ABBA", "Arrival", 0.80, 0.72, -4.0, 100.0),
        ("Take Me to Church", "Hozier", "Hozier", 0.50, 0.78, -7.6, 128.0),
        ("All Star", "Smash Mouth", "Fush Yu Mang", 0.58, 0.83, -3.76, 93.2),
        (
            "I Will Always Love You",
            "Whitney Houston",
            "The Bodyguard: Original Soundtrack Album",
            0.37,
            0.50,
            -12.0,
            66.0,
        ),
        (
            "Viva la Vida",
            "Coldplay",
            "Viva la Vida or Death and All His Friends",
            0.65,
            0.82,
            -7.0,
            138.0,
        ),
        (
            "Born in the U.S.A.",
            "Bruce Springsteen",
            "Born in the U.S.A.",
            0.58,
            0.88,
            -6.2,
            120.0,
        ),
        (
            "Thrift Shop",
            "Macklemore & Ryan Lewis ft. Wanz",
            "The Heist",
            0.75,
            0.86,
            -6.1,
            96.0,
        ),
        ("Crazy", "Gnarls Barkley", "St. Elsewhere", 0.82, 0.74, -5.0, 112.0),
        (
            "Can't Stop the Feeling!",
            "Justin Timberlake",
            "Trolls: Original Motion Picture Soundtrack",
            0.80,
            0.83,
            -5.2,
            113.0,
        ),
        ("Don't Stop Believin'", "Journey", "Escape", 0.75, 0.85, -5.0, 118.0),
        ("Shape of You", "Ed Sheeran", "÷", 0.82, 0.88, -3.5, 96.0),
        ("Billie Jean", "Michael Jackson", "Thriller", 0.77, 0.92, -5.5, 117.0),
        ("Bohemian Rhapsody", "Queen", "A Night at the Opera", 0.65, 0.75, -6.8, 76.0),
        (
            "Uptown Funk",
            "Mark Ronson ft. Bruno Mars",
            "Uptown Special",
            0.88,
            0.95,
            -4.2,
            115.0,
        ),
        (
            "Sweet Child o' Mine",
            "Guns N' Roses",
            "Appetite for Destruction",
            0.72,
            0.82,
            -6.3,
            125.0,
        ),
        (
            "I Will Always Love You",
            "Whitney Houston",
            "The Bodyguard",
            0.67,
            0.78,
            -7.2,
            60.0,
        ),
        ("Wannabe", "Spice Girls", "Spice", 0.76, 0.84, -5.0, 110.0),
        (
            "Shape of My Heart",
            "Backstreet Boys",
            "Black & Blue",
            0.73,
            0.81,
            -5.7,
            100.0,
        ),
        ("Smooth", "Santana ft. Rob Thomas", "Supernatural", 0.85, 0.90, -4.0, 116.0),
        (
            "Every Breath You Take",
            "The Police",
            "Synchronicity",
            0.68,
            0.79,
            -6.0,
            118.0,
        ),
        ("Rolling in the Deep", "Adele", "21", 0.74, 0.88, -5.2, 105.0),
        (
            "Livin' on a Prayer",
            "Bon Jovi",
            "Slippery When Wet",
            0.78,
            0.86,
            -4.5,
            123.0,
        ),
        (
            "I Gotta Feeling",
            "The Black Eyed Peas",
            "The E.N.D.",
            0.80,
            0.92,
            -4.0,
            128.0,
        ),
        ("Superstition", "Stevie Wonder", "Talking Book", 0.77, 0.87, -5.3, 105.0),
        ("Take on Me", "a-ha", "Hunting High and Low", 0.76, 0.85, -6.2, 170.0),
        ("Somebody to Love", "Queen", "A Day at the Races", 0.70, 0.80, -6.5, 110.0),
        (
            "I Want to Hold Your Hand",
            "The Beatles",
            "Meet the Beatles!",
            0.63,
            0.75,
            -7.0,
            128.0,
        ),
        (
            "Can't Stop the Feeling!",
            "Justin Timberlake",
            "Trolls (Original Motion Picture Soundtrack)",
            0.84,
            0.91,
            -4.2,
            113.0,
        ),
        ("Stayin' Alive", "Bee Gees", "Saturday Night Fever", 0.77, 0.88, -4.5, 103.0),
        ("Poker Face", "Lady Gaga", "The Fame", 0.79, 0.92, -4.7, 118.0),
        ("All About That Bass", "Meghan Trainor", "Title", 0.72, 0.83, -5.8, 134.0),
        ("Sorry", "Justin Bieber", "Purpose", 0.82, 0.88, -3.7, 100.0),
        ("Despacito", "Luis Fonsi ft. Daddy Yankee", "Vida", 0.85, 0.91, -4.3, 89.0),
        ("Hey Jude", "The Beatles", "The Beatles", 0.65, 0.77, -7.0, 120.0),
        (
            "I'm Yours",
            "Jason Mraz",
            "We Sing. We Dance. We Steal Things.",
            0.76,
            0.85,
            -5.0,
            150.0,
        ),
        (
            "Viva la Vida",
            "Coldplay",
            "Viva la Vida or Death and All His Friends",
            0.78,
            0.87,
            -5.2,
            138.0,
        ),
        ("Like a Virgin", "Madonna", "Like a Virgin", 0.74, 0.80, -6.2, 116.0),
        ("I Will Survive", "Gloria Gaynor", "Love Tracks", 0.76, 0.86, -5.0, 117.0),
        ("Firework", "Katy Perry", "Teenage Dream", 0.80, 0.89, -4.2, 124.0),
        ("Take Me to Church", "Hozier", "Hozier", 0.68, 0.78, -6.5, 128.0),
        (
            "Can't Help Falling in Love",
            "Elvis Presley",
            "Blue Hawaii",
            0.63,
            0.70,
            -9.0,
            87.0,
        ),
        (
            "Girls Just Want to Have Fun",
            "Cyndi Lauper",
            "She's So Unusual",
            0.85,
            0.88,
            -4.5,
            120.0,
        ),
        ("Waterloo", "ABBA", "Waterloo", 0.72, 0.82, -5.8, 145.0),
        ("All of Me", "John Legend", "Love in the Future", 0.69, 0.75, -6.5, 120.0),
        ("Dancing Queen", "ABBA", "Arrival", 0.80, 0.88, -4.0, 100.0),
        ("Counting Stars", "OneRepublic", "Native", 0.76, 0.85, -4.8, 122.0),
    ]

    song_pool = []
    for d in data:
        song = Song(*d)
        song_pool.append(song)

    return song_pool
